### ISSUE TITLE
SteamAPI_Init() failed; no appID found.

### ISSUE THREAD

**Issue by iAmThatMichael** [TreyarchGames/ModLauncher#2]
Since the Mod Tools call SteamAPI_Init() here: https://github.com/TreyarchGames/ModLauncher/blob/master/mlMainWindow.cpp#L185

Steam throws SteamAPI_Init() failed; no appID found.

The fix is to include steam_appid.txt into the bin folderas well.

Just thought of bringing this to attention.

**Comment by SE2Dev** [comment]
We could always force the creation of steam_appid.txt at runtime and then immediately delete it after SteamAPI initializes.

**Comment by TreyarchProgrammer** [comment]
You're right, I added a note to the README about this.
